{"name": "test_verify_created_invoice_status", "status": "failed", "statusDetails": {"message": "AssertionError: Locator expected to be visible\nActual value: <element(s) not found> \nCall log:\nLocatorAssertions.to_be_visible with timeout 5000ms\n  - waiting for locator(\"//div[contains(@class, 'text-truncate-w100') and contains(text(), 'invoicenumb1')]\")", "trace": "setup_and_teardown = <Page url='https://www.tig-test.com/my-frs/frs-invoices'>\n\n    def test_verify_created_invoice_status(setup_and_teardown) -> None:\n        page = setup_and_teardown\n        invoice_page = UploadInvoicePage(page)\n        try:\n            invoice_page.login(ExcelUtils.get_cell_data(\"ExcelFiles/Testdata.xlsx\", \"Login\", 2, 1),\n                               ExcelUtils.get_cell_data(\"ExcelFiles/Testdata.xlsx\", \"Login\", 2, 2))\n            invoice_page.search_invoice(ExcelUtils.get_cell_data(\"ExcelFiles/Testdata.xlsx\", \"Invoice\", 2, 1))\n            time.sleep(3)\n>           invoice_page.verify_invoice_in_list(ExcelUtils.get_cell_data(\"ExcelFiles/Testdata.xlsx\", \"Invoice\", 2, 1))\n\ntests/test_Upload_invoice.py:33: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pages.UploadInvoicePage.UploadInvoicePage object at 0x7f5542808910>, keyword = 'invoicenumb1'\n\n    def verify_invoice_in_list(self, keyword: str) -> None:\n        try:\n            element = self.page.locator(\n                f\"//div[contains(@class, 'text-truncate-w100') and contains(text(), '{keyword}')]\")\n>           expect(element).to_be_visible()\nE           AssertionError: Locator expected to be visible\nE           Actual value: <element(s) not found> \nE           Call log:\nE           LocatorAssertions.to_be_visible with timeout 5000ms\nE             - waiting for locator(\"//div[contains(@class, 'text-truncate-w100') and contains(text(), 'invoicenumb1')]\")\n\npages/UploadInvoicePage.py:104: AssertionError"}, "attachments": [{"name": "stdout", "source": "248d3d9c-a2a0-485f-8e1d-9d1dda992be3-attachment.txt", "type": "text/plain"}], "start": 1720431255093, "stop": 1720431268680, "uuid": "02f34078-a0fd-4501-898e-be70a94aeecb", "historyId": "0a6e48d5408d613d4f1eeb54af380e68", "testCaseId": "0a6e48d5408d613d4f1eeb54af380e68", "fullName": "tests.test_Upload_invoice#test_verify_created_invoice_status", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_Upload_invoice"}, {"name": "host", "value": "laptop-obs-156"}, {"name": "thread", "value": "113532-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_Upload_invoice"}]}